=== adrianalex48/liga-mx-xml/xml/dtd/resultados.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT jornada (partido+)>
<!ATTLIST jornada
    numero CDATA #REQUIRED
    fecha CDATA #REQUIRED
    liga CDATA #REQUIRED>

<!ELEMENT partido (local, visitante, arbitro?, estadisticas?)>
<!ATTLIST partido
    id ID #REQUIRED
    estadio CDATA #REQUIRED
    estado CDATA #REQUIRED>

<!ELEMENT local EMPTY>
<!ATTLIST local
    nombre CDATA #REQUIRED
    goles CDATA #REQUIRED>

<!ELEMENT visitante EMPTY>
<!ATTLIST visitante
    nombre CDATA #REQUIRED
    goles CDATA #REQUIRED>

<!ELEMENT arbitro (#PCDATA)>

<!ELEMENT estadisticas (posesion, tiros, tiros_puerta, faltas, tarjetas_amarillas, tarjetas_rojas)>
<!ELEMENT posesion (#PCDATA)>
<!ELEMENT tiros (#PCDATA)>
<!ELEMENT tiros_puerta (#PCDATA)>
<!ELEMENT faltas (#PCDATA)>
<!ELEMENT tarjetas_amarillas (#PCDATA)>
<!ELEMENT tarjetas_rojas (#PCDATA)>

=== adrianalex48/liga-mx-xml/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jornada SYSTEM "../dtd/resultados.dtd">
<jornada numero="10" fecha="2026-09-27" liga="Liga MX">
    <partido id="p1" estadio="Estadio Azteca" estado="Finalizado">
        <local nombre="Club América" goles="2"/>
        <visitante nombre="Guadalajara" goles="1"/>
        <arbitro>Fernando Guerrero</arbitro>
        <estadisticas>
            <posesion>54%</posesion>
            <tiros>14</tiros>
            <tiros_puerta>6</tiros_puerta>
            <faltas>12</faltas>
            <tarjetas_amarillas>3</tarjetas_amarillas>
            <tarjetas_rojas>0</tarjetas_rojas>
        </estadisticas>
    </partido>
    <partido id="p2" estadio="Estadio Universitario" estado="Finalizado">
        <local nombre="Tigres UANL" goles="0"/>
        <visitante nombre="Monterrey" goles="0"/>
        <arbitro>César Arturo Ramos</arbitro>
        <estadisticas>
            <posesion>50%</posesion>
            <tiros>10</tiros>
            <tiros_puerta>3</tiros_puerta>
            <faltas>15</faltas>
            <tarjetas_amarillas>4</tarjetas_amarillas>
            <tarjetas_rojas>1</tarjetas_rojas>
        </estadisticas>
    </partido>
</jornada>
